# -*- coding: utf-8 -*-
"""лаб1_Бахтин.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZwGzWw87t6_IvdEM4GlWOF2oPkDY_XH

#Разведочный анализ с использованием pandas

- используемый датасет: Travel Reviews (https://archive.ics.uci.edu/dataset/484/travel+reviews)

задание:
- скачать один из наборов данных 👾
- загрузить данные в датафрейм 👾
- вывести статистическую информацию о наборе данных 👾
- вывести названия столбцов и строк 👾
- заменить категориальные данные количественными 👾 *(в данном датасете их нет) (пустых ячеек тоже нет)*
- визуализировать данные с помощью Matplotlib и Seaborn 👾
-- не менее 2х визуализаций на каждый признак 👾
-- не менее 3х групповых визуализаций 👾
"""

pip install ucimlrepo

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()  # устанавливаем seaborn по умолчанию для отрисовки графиков

class colors:
    purp = '\033[95m'  # Purple color
    blue = '\033[94m'  # Blue color
    green = '\033[92m'  # Green color
    yell = '\033[93m'  # Yellow color
    red = '\033[91m'  # Red color
    fiolet = '\033[35m'
    bold = '\033[1m'  # Bold
    uline = '\033[4m'  # Underline
    endc = '\033[0m'  # End of color line

from ucimlrepo import fetch_ucirepo

# fetch dataset
travel_reviews = fetch_ucirepo(id=484)

# data (as pandas dataframes)
train = travel_reviews.data.features
y = travel_reviews.data.targets

# metadata
#print(travel_reviews.metadata)

print(f"{colors.blue}{colors.bold}Поясняющая информация{colors.endc}")
print(travel_reviews.variables)

#print(f"{colors.purp}{colors.bold}\n\nИсходный датасет{colors.endc}")
#with pd.option_context('display.max_columns', None):
#  display(X)

train.rename(columns = {'Category 1':'Art galleries', 'Category 2': 'Dance clubs', 'Category 3': 'Juice bars', 'Category 4' : 'Restaurants', 'Category 5': 'Museums', 'Category 6': 'Resorts', 'Category 7': 'Parks/picnic spots', 'Category 8': 'beaches', 'Category 9': 'Theaters', 'Category 10': 'Religious institutions' }, inplace = True )

print(f"{colors.purp}{colors.bold}\n\nДАТАСЕТ{colors.endc}")
with pd.option_context('display.max_columns', None):
  display(train)

train.describe()

"""с помощью этого метода посмотрели на статистику датасета - среднее, максимальное/минимальное значения в каждой из категорий/столбцов"""

#train.describe(include=['O']) #для нечисловых данных

"""т.к. в данном датасете нет нечисловых данных, то вышеописанный метод не использую"""

train.info()

"""Здесь вывели следующую информацию: названия столбцов, типы данных в них, количество непустых записей и т.п.

## Визуализация распределений и взаимосвязей

###визуализация признаков
"""

#по всем признакам
for i in train.columns:
  train.plot(y=i, color='green')

#АРТ-ГАЛЕРЕИ

#график количества оценок
plt.figure(figsize=(40, 5))
sns.countplot(x='Art galleries', data=train, color='yellow')

#разделили по количеству на "положительные" и "отрицательные" оценки
avg = round(train['Art galleries'].mean(), 2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['Art galleries'].items():
    if value >= avg:
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1

plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['pink', 'violet'])
plt.tight_layout()

#ДЭНС КЛУБЫ

plt.figure(figsize=(7, 3))
means = pd.cut(train['Dance clubs'], bins=[0, 1, 2, 3], labels=['0-1', '1-2', '2-3'])
sns.countplot(x=means, color='green')

#разделили по количеству на "положительные" и "отрицательные" оценки
avg = round(train['Dance clubs'].mean(), 2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['Dance clubs'].items():
    if value >= avg:
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1

plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['orange', 'yellow'])
plt.tight_layout()

#ДЖУС БАРЫ

plt.figure(figsize=(7, 3))
means = pd.cut(train['Juice bars'], bins=[0, 1, 2, 3], labels=['0-1', '1-2', '2-3'])
sns.countplot(x=means, color='blue')

avg = round(train['Juice bars'].mean(), 2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['Juice bars'].items():
    if value >= avg:
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1

plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['tomato', 'gold'])
plt.tight_layout()

#РЕСТОРАНЫ

plt.figure(figsize=(7, 3))
means = pd.cut(train['Restaurants'], bins=[0, 1, 2, 3], labels=['0-1', '1-2', '2-3'])
sns.countplot(x=means, color='#77BFE2')

avg = round(train['Restaurants'].mean(), 2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['Restaurants'].items():
    if value >= avg:
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1

plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['#77FAF0', '#90AAE9'])
plt.tight_layout()

#МУЗЕИ
plt.figure(figsize=(7, 3))
means = pd.cut(train['Museums'], bins=[0, 1, 2, 3], labels=['0-1', '1-2', '2-3'])
sns.countplot(x=means, color='#FFFEA5')

avg = round(train['Museums'].mean(), 2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['Museums'].items():
    if value >= avg:
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1

plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['#BA1FA6', '#9BAAAA'])
plt.tight_layout()

#КУРОРТЫ

plt.figure(figsize=(7, 3))
means = pd.cut(train['Resorts'], bins=[0, 1, 2, 3, 4, 5], labels=['0-1', '1-2', '2-3', '3-4', '4-5'])
sns.countplot(x=means, color='#3BFA95')

avg = round(train['Resorts'].mean(),2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['Resorts'].items():
    if value >= avg:
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1

plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['#AAFFA9', '#2BF99A'])
plt.tight_layout()

#ПАРКИ, МЕСТА ДЛЯ ПИКНИКОВ

plt.figure(figsize=(7, 3))
sns.countplot(x='Parks/picnic spots', data=train, color='#FFAA21')

avg = round(train['Parks/picnic spots'].mean(), 2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['Parks/picnic spots'].items():
    if (value >= avg):
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1


plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['#32C0F1', '#2BFFCA'])
plt.tight_layout()

#ДЛЯ ПЛЯЖЕЙ

plt.figure(figsize=(7, 3))
means = pd.cut(train['beaches'], bins=[0, 1, 2, 3, 4, 5], labels=['0-1', '1-2', '2-3', '3-4', '4-5'])
sns.countplot(x=means, color='#EF0099')

avg = round(train['beaches'].mean(),2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['beaches'].items():
    if value >= avg:
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1

plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['#ABBFC2', '#CCFA9A'])
plt.tight_layout()

#ТЕАТРЫ

plt.figure(figsize=(10, 5))
train.boxplot(column='Theaters', grid=True, color='blue')

avg = round(train['Theaters'].mean(),2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['Theaters'].items():
    if value >= avg:
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1

plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['#ABA0C2', '#AA119A'])
plt.tight_layout()

#РЕЛИГИОЗНЫЕ УЧРЕЖДЕНИЯ
plt.figure(figsize=(10, 5))
train.boxplot(column='Religious institutions', grid=True, color='violet')

avg = round(train['Religious institutions'].mean(),2)
list_values = {'sum_above': 0, 'sum_below': 0}
for index, value in train['Religious institutions'].items():
    if value >= avg:
      list_values['sum_above'] += 1
    else:
      list_values['sum_below'] += 1

plt.title('Соотношение оценок выше и ниже среднего')
plt.pie(list_values.values(), labels=list_values.keys(), autopct='%1.1f%%', colors=['#ABFF52', '#CFF13A'])
plt.tight_layout()

"""###групповая визуализация"""

#тепловая карта с корреляций признаков, чтобы посмотреть что и как взаимосвязано между собой
sns.heatmap(train.corr(numeric_only = True), cmap="magma");

df = train[['Juice bars', 'Parks/picnic spots']]
#display(df)
#plt.figure(figsize=(10, 5))

sns.scatterplot(data=df, x='Juice bars', y='Parks/picnic spots', alpha=0.5)

plt.title('Зависимость оценки на Parks/picnic от оценки на Juice bars')
plt.tight_layout()

df2 = train[['Resorts', 'Religious institutions']]
sns.scatterplot(data=df2, x='Resorts', y='Religious institutions', alpha=0.5)

plt.title('Зависимость оценки на Religious institutions от оценки на Resorts')
plt.tight_layout()